# Generated by Django 4.2.2 on 2023-06-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_alter_client_date_created_alter_client_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('NW', 'New'), ('EX', 'Existing')], default='NW', max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClientType',
        ),
    ]
