# Generated by Django 4.2.2 on 2023-07-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0004_alter_client_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='payment_due',
            field=models.DateTimeField(),
        ),
    ]
