# Generated by Django 4.2.2 on 2023-07-10 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0005_alter_client_date_created_alter_client_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='payment_due',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{2}/\\d{2}/\\d{4}$', 'Veuillez entrer une date au format JJ/MM/AAAA.')]),
        ),
    ]
