# Generated by Django 4.2.2 on 2023-07-17 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0008_alter_contrat_sales_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_type',
        ),
    ]
