# Generated by Django 4.2.2 on 2023-07-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0009_remove_client_client_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='status',
            field=models.CharField(choices=[('SI', 'Signé'), ('DR', 'Devis a réaliser'), ('DE', 'Devis envoyé')], default='DR', max_length=2),
        ),
    ]
