# Generated by Django 4.2.2 on 2023-07-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0010_alter_contrat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='amount',
        ),
        migrations.AddField(
            model_name='contrat',
            name='amount_in_euros',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
            preserve_default=False,
        ),
    ]
