# Generated by Django 4.2.2 on 2023-07-18 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0011_remove_contrat_amount_contrat_amount_in_euros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='payment_due',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}/\\d{2}/\\d{4}$', 'Veuillez entrer une date au format JJ/MM/AAAA.')]),
        ),
    ]
