# Generated by Django 4.2.2 on 2023-07-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0012_alter_contrat_payment_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='amount_in_euros',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
