# Generated by Django 4.2.2 on 2023-06-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile',
            field=models.CharField(choices=[('GE', 'Gestion'), ('SA', 'Vente'), ('SU', 'Support')], default='SA', max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfiles',
        ),
    ]
