# Generated by Django 4.2.2 on 2023-06-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('évènements', '0003_alter_event_date_created_alter_event_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('PR', 'Preparation'), ('IP', 'In progress'), ('FN', 'Finished')], default='IP', max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventStatus',
        ),
    ]
