# Generated by Django 4.2.2 on 2023-07-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('évènements', '0005_alter_event_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
