# Generated by Django 4.2.2 on 2023-07-11 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('évènements', '0006_alter_event_date_created_alter_event_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{2}/\\d{2}/\\d{4}$', 'Veuillez entrer une date au format JJ/MM/AAAA.')]),
        ),
    ]
