# Generated by Django 4.2.2 on 2023-07-21 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0013_alter_contrat_amount_in_euros'),
        ('évènements', '0008_alter_event_support_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contrat',
            field=models.OneToOneField(default=8, on_delete=django.db.models.deletion.CASCADE, to='contrats.contrat'),
            preserve_default=False,
        ),
    ]
